<div class="text-white text-center drop-shadow margin-top-sm @if ($widget->state != 'loading') not-visible @endif" id="widget-loading-{{ $widget->id }}">
    <i class="fa fa-circle-o-notch fa-spin"></i> Loading....
</div>
